export type TripStatus = "planned" | "wishlist" | "completed";

export interface TripStop {
  name: string;
  lat: number;
  lng: number;
  day: string;
  altitude?: string;
}

export interface TripDay {
  day: number;
  title: string;
  subtitle: string;
  description: string;
  points: string[];
  photo: string;
  photoCaption: string;
  distance?: string;
  driveTime?: string;
  altitude?: string;
}

export interface Trip {
  slug: string;
  title: string;
  titleEn: string;
  region: string;
  country: string;
  cover: string;
  description: string;
  status: TripStatus;
  days: number;
  style: string;
  highlights: string[];
  gradient: string;
  bestSeason: string;
  budget?: string;
  detailDays?: TripDay[];
  stops?: TripStop[];
  packingList?: string[];
  tips?: string[];
  photoTips?: { spot: string; time: string }[];
}

export const trips: Trip[] = [
  {
    slug: "qinghai",
    title: "青海自駕",
    titleEn: "Qinghai Roadtrip",
    region: "西北",
    country: "中國",
    cover: "https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?auto=format&fit=crop&w=1200&q=80",
    description: "主打攝影感的 4 天 3 夜青海自駕路線，涵蓋青海湖、茶卡鹽湖、黑獨山、翡翠湖與 U 型公路。",
    status: "planned",
    days: 4,
    style: "攝影系自駕",
    highlights: ["青海湖", "茶卡鹽湖", "黑獨山", "翡翠湖", "U 型公路"],
    gradient: "from-blue-600 to-cyan-400",
    bestSeason: "6–9 月",
    budget: "¥4,000–6,000 / 人",
    detailDays: [
      {
        day: 1,
        title: "西寧 → 青海湖 → 茶卡鎮",
        subtitle: "湖景開場日",
        description: "建議早上西寧取車出發，沿路先適應海拔，不要第一天太拼。",
        points: ["沿日月山方向出發", "青海湖多停幾個觀景位，不要只打一個卡", "傍晚前到茶卡鎮休息"],
        photo: "https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?auto=format&fit=crop&w=1200&q=80",
        photoCaption: "拍攝重點：青海湖公路、草原、湖面藍色層次",
        distance: "~280 km",
        driveTime: "~4.5 小時",
        altitude: "2,200→3,200 m",
      },
      {
        day: 2,
        title: "茶卡鹽湖 → 德令哈 → 黑獨山",
        subtitle: "倒影 + 荒漠大片日",
        description: "早上玩茶卡鹽湖，下午再去黑獨山，光線會更有層次。",
        points: ["茶卡鹽湖建議早些入場，較少人", "下午前往德令哈方向", "黃昏前到黑獨山拍荒漠感", "晚上住德令哈或大柴旦"],
        photo: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
        photoCaption: "拍攝重點：茶卡倒影、黑灰山體、日落前陰影層次",
        distance: "~350 km",
        driveTime: "~5 小時",
        altitude: "3,100→2,800 m",
      },
      {
        day: 3,
        title: "大柴旦 → 翡翠湖 → U 型公路",
        subtitle: "全程最出片的一天",
        description: "這天主打大景與顏色，翡翠湖最吃天氣，晴天效果最好。",
        points: ["上午先去翡翠湖", "下午去 U 型公路，但切記不要危險停車", "晚上回大柴旦休息"],
        photo: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80",
        photoCaption: "拍攝重點：翡翠湖藍綠水色、白色鹽地、公路延伸感",
        distance: "~180 km",
        driveTime: "~3 小時",
        altitude: "3,150 m",
      },
      {
        day: 4,
        title: "大柴旦 → 沿途景觀 → 西寧",
        subtitle: "回程收尾日",
        description: "這天以安全返程為主，不建議再硬塞太多點。",
        points: ["沿途視體力停景觀位", "如果季節適合，可留意門源一帶景色", "晚上回西寧還車"],
        photo: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
        photoCaption: "拍攝重點：雪山遠景、草原線條、旅程結尾公路感",
        distance: "~750 km",
        driveTime: "~9 小時",
        altitude: "3,150→2,200 m",
      },
    ],
    stops: [
      { name: "西寧", lat: 36.617, lng: 101.778, day: "D1 起點", altitude: "2,200m" },
      { name: "日月山", lat: 36.643, lng: 101.093, day: "D1 途經", altitude: "3,520m" },
      { name: "青海湖", lat: 36.887, lng: 100.135, day: "D1 景點", altitude: "3,200m" },
      { name: "茶卡鎮", lat: 36.767, lng: 99.117, day: "D1 住宿", altitude: "3,059m" },
      { name: "茶卡鹽湖", lat: 36.72, lng: 99.08, day: "D2 景點", altitude: "3,100m" },
      { name: "德令哈", lat: 37.37, lng: 97.37, day: "D2 途經", altitude: "2,980m" },
      { name: "黑獨山", lat: 37.44, lng: 97.1, day: "D2 景點", altitude: "3,000m" },
      { name: "大柴旦", lat: 37.85, lng: 95.36, day: "D2 住宿 / D3", altitude: "3,150m" },
      { name: "翡翠湖", lat: 37.88, lng: 95.35, day: "D3 景點", altitude: "3,150m" },
      { name: "U 型公路", lat: 37.62, lng: 95.9, day: "D3 景點", altitude: "3,100m" },
    ],
    packingList: [
      "防曬霜 SPF50+", "墨鏡（偏光）", "保暖外套", "潤唇膏",
      "充電寶 + 車充", "氧氣罐", "葡萄糖沖劑", "水（每日 2L）",
      "現金（偏遠區）", "離線地圖", "相機 + 備用電池", "三腳架",
      "急救包", "零食乾糧", "身份證 / 回鄉證",
    ],
    tips: [
      "青海海拔高，第一天唔好太搏",
      "見油站就補油，不要拖到太後",
      "黑獨山等偏位訊號未必穩",
      "U 型公路不要亂停中間影相",
      "帶防曬、墨鏡、外套、潤唇膏、水",
    ],
    photoTips: [
      { spot: "青海湖", time: "下午 4–7 點較靚" },
      { spot: "茶卡鹽湖", time: "早上或傍晚" },
      { spot: "黑獨山", time: "黃昏前後最好" },
      { spot: "翡翠湖", time: "中午到下午色更出" },
      { spot: "U 型公路", time: "早晚都靚，但安全第一" },
    ],
  },
  {
    slug: "iceland",
    title: "冰與火之國",
    titleEn: "Iceland Ring Road",
    region: "北歐",
    country: "冰島",
    cover: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1200&q=80",
    description: "環島一號公路自駕，追極光、看冰川、泡溫泉，感受地球最原始的風景。",
    status: "completed",
    days: 10,
    style: "自駕探險",
    highlights: ["藍湖溫泉", "黃金圈", "冰河湖", "黑沙灘", "極光"],
    gradient: "from-indigo-600 to-purple-400",
    bestSeason: "9–3 月（極光）/ 6–8 月（日照）",
  },
  {
    slug: "japan-sakura",
    title: "追櫻之旅",
    titleEn: "Japan Cherry Blossom",
    region: "東亞",
    country: "日本",
    cover: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    description: "從東京到京都，追隨櫻花前線北上，體驗最日式的春天浪漫。",
    status: "completed",
    days: 8,
    style: "文化攝影",
    highlights: ["目黑川", "新宿御苑", "嵐山", "哲學之道", "吉野山"],
    gradient: "from-pink-500 to-rose-300",
    bestSeason: "3 月下旬 – 4 月中",
  },
  {
    slug: "new-zealand",
    title: "中土世界自駕",
    titleEn: "NZ South Island",
    region: "大洋洲",
    country: "紐西蘭",
    cover: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80",
    description: "南島自駕穿越雪山、冰川、星空與峽灣，每一段公路都是大片。",
    status: "completed",
    days: 12,
    style: "自然探索",
    highlights: ["米佛峽灣", "庫克山", "皇后鎮", "蒂卡波湖", "冰川"],
    gradient: "from-emerald-600 to-teal-400",
    bestSeason: "11–3 月（夏季）",
  },
  {
    slug: "norway-fjords",
    title: "挪威峽灣",
    titleEn: "Norway Fjords",
    region: "北歐",
    country: "挪威",
    cover: "https://images.unsplash.com/photo-1520769669658-f07657f5a307?auto=format&fit=crop&w=1200&q=80",
    description: "峽灣巡遊加懸崖徒步，奇跡石、布道石、巨人之舌，挑戰自己的極限風景。",
    status: "wishlist",
    days: 9,
    style: "徒步冒險",
    highlights: ["蓋朗厄爾峽灣", "布道石", "奇跡石", "羅弗敦群島", "巨人之舌"],
    gradient: "from-sky-600 to-blue-400",
    bestSeason: "6–8 月",
  },
  {
    slug: "patagonia",
    title: "巴塔哥尼亞",
    titleEn: "Patagonia",
    region: "南美",
    country: "智利 / 阿根廷",
    cover: "https://images.unsplash.com/photo-1509660933844-6910e12765a0?auto=format&fit=crop&w=1200&q=80",
    description: "世界盡頭的壯闊風景：Torres del Paine、Perito Moreno 冰川、風之大地。",
    status: "wishlist",
    days: 14,
    style: "徒步野營",
    highlights: ["百內塔", "莫雷諾冰川", "菲茨羅伊峰", "火地島", "企鵝島"],
    gradient: "from-amber-600 to-orange-400",
    bestSeason: "11–3 月（夏季）",
  },
  {
    slug: "morocco",
    title: "摩洛哥",
    titleEn: "Morocco",
    region: "北非",
    country: "摩洛哥",
    cover: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=1200&q=80",
    description: "藍色小鎮、撒哈拉沙漠、馬拉喀什老城，色彩與異域文化的極致體驗。",
    status: "wishlist",
    days: 7,
    style: "文化探索",
    highlights: ["舍夫沙萬", "撒哈拉沙漠", "馬拉喀什", "菲斯老城", "艾本哈度"],
    gradient: "from-red-500 to-yellow-400",
    bestSeason: "3–5 月 / 9–11 月",
  },
  {
    slug: "swiss-alps",
    title: "瑞士阿爾卑斯",
    titleEn: "Swiss Alps",
    region: "歐洲",
    country: "瑞士",
    cover: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80",
    description: "火車穿越阿爾卑斯，少女峰、馬特洪峰、琉森湖，每一幀都是明信片。",
    status: "wishlist",
    days: 8,
    style: "鐵路漫遊",
    highlights: ["少女峰", "馬特洪峰", "琉森湖", "冰河快車", "因特拉肯"],
    gradient: "from-slate-600 to-zinc-400",
    bestSeason: "6–9 月（夏季）/ 12–3 月（滑雪）",
  },
  {
    slug: "germany",
    title: "德國",
    titleEn: "Germany",
    region: "歐洲",
    country: "德國",
    cover: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80",
    description: "新天鵝堡、黑森林、慕尼黑啤酒節、柏林圍牆，歷史與童話交織的國度。",
    status: "wishlist",
    days: 10,
    style: "文化自駕",
    highlights: ["新天鵝堡", "黑森林", "慕尼黑", "柏林", "萊茵河谷"],
    gradient: "from-yellow-600 to-amber-400",
    bestSeason: "5–10 月 / 12 月（聖誕市集）",
  },
  {
    slug: "spain",
    title: "熱情伊比利亞",
    titleEn: "Spain",
    region: "歐洲",
    country: "西班牙",
    cover: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1200&q=80",
    description: "高第建築、佛朗明哥、地中海陽光、Tapas 美食，熱情奔放的伊比利亞半島。",
    status: "completed",
    days: 10,
    style: "文化美食",
    highlights: ["聖家堂", "阿爾罕布拉宮", "聖地亞哥朝聖路", "塞維利亞", "聖塞巴斯蒂安"],
    gradient: "from-red-600 to-orange-400",
    bestSeason: "4–6 月 / 9–10 月",
  },
  {
    slug: "greece",
    title: "愛琴海漫遊",
    titleEn: "Greece",
    region: "歐洲",
    country: "希臘",
    cover: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    description: "聖托里尼藍白屋頂、雅典衛城、愛琴海跳島，地中海的浪漫極致。",
    status: "completed",
    days: 9,
    style: "海島漫遊",
    highlights: ["聖托里尼", "雅典衛城", "米克諾斯", "克里特島", "梅特歐拉"],
    gradient: "from-blue-500 to-cyan-300",
    bestSeason: "5–10 月",
  },
  {
    slug: "belgium",
    title: "比利時",
    titleEn: "Belgium",
    region: "歐洲",
    country: "比利時",
    cover: "https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=1200&q=80",
    description: "巧克力、啤酒、鬆餅與中世紀古城，小國家大驚喜。",
    status: "wishlist",
    days: 5,
    style: "城市漫步",
    highlights: ["布魯日", "布魯塞爾大廣場", "根特", "安特衛普", "比利時巧克力"],
    gradient: "from-amber-500 to-yellow-300",
    bestSeason: "4–10 月",
  },
  {
    slug: "egypt",
    title: "埃及",
    titleEn: "Egypt",
    region: "北非",
    country: "埃及",
    cover: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?auto=format&fit=crop&w=1200&q=80",
    description: "金字塔、尼羅河、帝王谷、盧克索神廟，走進千年法老的文明。",
    status: "wishlist",
    days: 8,
    style: "歷史探索",
    highlights: ["吉薩金字塔", "帝王谷", "盧克索神廟", "阿布辛貝", "尼羅河遊船"],
    gradient: "from-yellow-700 to-amber-500",
    bestSeason: "10–4 月",
  },
  {
    slug: "russia",
    title: "俄羅斯",
    titleEn: "Russia",
    region: "歐亞",
    country: "俄羅斯",
    cover: "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1200&q=80",
    description: "洋蔥頭教堂、西伯利亞鐵路、冬宮博物館、貝加爾湖冰封奇景。",
    status: "wishlist",
    days: 12,
    style: "鐵路深度",
    highlights: ["莫斯科紅場", "聖彼得堡冬宮", "貝加爾湖", "西伯利亞鐵路", "金環古城"],
    gradient: "from-red-700 to-blue-500",
    bestSeason: "6–8 月（夏）/ 1–2 月（冬景）",
  },
  {
    slug: "kenya-safari",
    title: "東非草原",
    titleEn: "Kenya Safari",
    region: "東非",
    country: "肯尼亞 / 坦桑尼亞",
    cover: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    description: "大遷徙、馬賽馬拉、塞倫蓋蒂、乞力馬扎羅，與野生動物面對面。",
    status: "wishlist",
    days: 10,
    style: "野生動物",
    highlights: ["馬賽馬拉", "塞倫蓋蒂", "恩戈羅恩戈羅", "乞力馬扎羅", "大遷徙"],
    gradient: "from-green-700 to-yellow-500",
    bestSeason: "7–10 月（大遷徙）",
  },
  {
    slug: "portugal",
    title: "大西洋的盡頭",
    titleEn: "Portugal",
    region: "歐洲",
    country: "葡萄牙",
    cover: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=80",
    description: "里斯本電車、波爾圖酒莊、大西洋海岸線、蛋撻發源地，低調浪漫的歐洲寶藏。",
    status: "completed",
    days: 7,
    style: "城市漫遊",
    highlights: ["里斯本", "波爾圖", "辛特拉", "阿爾加維海岸", "馬德拉島"],
    gradient: "from-teal-600 to-emerald-400",
    bestSeason: "4–10 月",
  },
  {
    slug: "finland",
    title: "芬蘭",
    titleEn: "Finland",
    region: "北歐",
    country: "芬蘭",
    cover: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80",
    description: "極光、玻璃屋、聖誕老人村、桑拿文化，北極圈內的夢幻冬日。",
    status: "wishlist",
    days: 7,
    style: "極地體驗",
    highlights: ["羅瓦涅米聖誕村", "玻璃穹頂屋", "極光", "破冰船", "赫爾辛基"],
    gradient: "from-indigo-500 to-cyan-300",
    bestSeason: "12–3 月（極光冬景）/ 6–8 月（日不落）",
  },
  {
    slug: "fiji",
    title: "斐濟",
    titleEn: "Fiji",
    region: "大洋洲",
    country: "斐濟",
    cover: "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&w=1200&q=80",
    description: "南太平洋的天堂海島，清澈到不真實的海水、珊瑚礁與世外桃源度假村。",
    status: "wishlist",
    days: 7,
    style: "海島度假",
    highlights: ["瑪瑪努卡群島", "亞薩瓦群島", "珊瑚礁浮潛", "日落沙灘", "傳統Kava儀式"],
    gradient: "from-cyan-400 to-blue-300",
    bestSeason: "5–11 月（旱季）",
  },
  {
    slug: "chile",
    title: "智利",
    titleEn: "Chile",
    region: "南美",
    country: "智利",
    cover: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?auto=format&fit=crop&w=1200&q=80",
    description: "從阿塔卡馬沙漠到巴塔哥尼亞冰川，全球最狹長國家的極端風景。",
    status: "wishlist",
    days: 12,
    style: "自然探險",
    highlights: ["阿塔卡馬沙漠", "百內國家公園", "復活節島", "瓦爾帕萊索", "星空觀測"],
    gradient: "from-red-500 to-blue-400",
    bestSeason: "11–3 月（夏季）",
  },
  {
    slug: "bolivia",
    title: "玻利維亞",
    titleEn: "Bolivia",
    region: "南美",
    country: "玻利維亞",
    cover: "https://images.unsplash.com/photo-1619441207978-3d326c46e2c9?auto=format&fit=crop&w=1200&q=80",
    description: "天空之鏡烏尤尼鹽湖、拉巴斯空中纜車、彩色山谷，南美最超現實的國度。",
    status: "wishlist",
    days: 8,
    style: "攝影冒險",
    highlights: ["烏尤尼鹽湖", "拉巴斯", "的的喀喀湖", "月亮谷", "彩色山谷"],
    gradient: "from-sky-300 to-white",
    bestSeason: "12–3 月（雨季天空之鏡）/ 5–10 月（旱季）",
  },
  {
    slug: "colombia",
    title: "哥倫比亞",
    titleEn: "Colombia",
    region: "南美",
    country: "哥倫比亞",
    cover: "https://images.ctfassets.net/u4n3py88yqgb/2yWe2tsvqPkOEj6gw0tAE/363392b1d2d98aeaf96092345a05af3f/Untitled_design__11_.png?w=1200&fm=webp",
    description: "五彩繽紛的卡塔赫納老城、咖啡產區、彩虹河、加勒比海岸，南美最被低估的寶藏。",
    status: "wishlist",
    days: 10,
    style: "文化探索",
    highlights: ["卡塔赫納", "波哥大", "咖啡產區", "彩虹河", "聖安德烈斯島"],
    gradient: "from-yellow-400 to-blue-500",
    bestSeason: "12–3 月 / 7–8 月（旱季）",
  },
  {
    slug: "argentina",
    title: "阿根廷",
    titleEn: "Argentina",
    region: "南美",
    country: "阿根廷",
    cover: "https://images.unsplash.com/photo-1612294037637-ec328d0e075e?auto=format&fit=crop&w=1200&q=80",
    description: "探戈發源地、莫雷諾冰川、伊瓜蘇瀑布、門多薩酒莊，南美最歐洲的國家。",
    status: "wishlist",
    days: 12,
    style: "自然文化",
    highlights: ["布宜諾斯艾利斯", "伊瓜蘇瀑布", "莫雷諾冰川", "門多薩酒莊", "烏斯懷亞"],
    gradient: "from-sky-400 to-white",
    bestSeason: "10–4 月",
  },
  {
    slug: "mexico",
    title: "墨西哥",
    titleEn: "Mexico",
    region: "中美",
    country: "墨西哥",
    cover: "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=1200&q=80",
    description: "瑪雅金字塔、天然溶井、亡靈節、Taco美食，古文明與色彩的碰撞。",
    status: "wishlist",
    days: 10,
    style: "文化冒險",
    highlights: ["奇琴伊察", "坎昆", "墨西哥城", "瓜納華托", "天然溶井"],
    gradient: "from-green-600 to-red-500",
    bestSeason: "11–4 月（旱季）",
  },
  {
    slug: "brazil",
    title: "巴西",
    titleEn: "Brazil",
    region: "南美",
    country: "巴西",
    cover: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80",
    description: "基督像、科帕卡巴納海灘、亞馬遜雨林、伊瓜蘇瀑布，南美最大國的震撼。",
    status: "wishlist",
    days: 12,
    style: "自然文化",
    highlights: ["里約基督像", "伊瓜蘇瀑布", "亞馬遜雨林", "薩爾瓦多", "聖保羅"],
    gradient: "from-green-500 to-yellow-400",
    bestSeason: "5–9 月（旱季）/ 2 月（嘉年華）",
  },
  {
    slug: "thailand",
    title: "微笑國度",
    titleEn: "Thailand",
    region: "東南亞",
    country: "泰國",
    cover: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1200&q=80",
    description: "曼谷的廟宇與夜市、清邁的古城與山林，去了又去的東南亞後花園。",
    status: "completed",
    days: 5,
    style: "城市休閒",
    highlights: ["曼谷大皇宮", "清邁古城", "夜市美食", "水上市場", "寺廟巡禮"],
    gradient: "from-yellow-500 to-orange-400",
    bestSeason: "11–2 月",
  },
  {
    slug: "south-korea",
    title: "韓流之旅",
    titleEn: "South Korea",
    region: "東亞",
    country: "韓國",
    cover: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1200&q=80",
    description: "首爾的潮流與釜山的海岸，從仁川到慶州，韓式文化的深度體驗。",
    status: "completed",
    days: 5,
    style: "文化美食",
    highlights: ["首爾", "釜山", "景福宮", "明洞", "韓式烤肉"],
    gradient: "from-blue-600 to-red-400",
    bestSeason: "3–5 月 / 9–11 月",
  },
  {
    slug: "vietnam",
    title: "越南風情",
    titleEn: "Vietnam",
    region: "東南亞",
    country: "越南",
    cover: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?auto=format&fit=crop&w=1200&q=80",
    description: "河內老城的法式風情、越南河粉的味道，摩托車穿梭的東南亞魅力。",
    status: "completed",
    days: 5,
    style: "文化美食",
    highlights: ["河內老城", "下龍灣", "越南河粉", "還劍湖", "法式建築"],
    gradient: "from-red-600 to-yellow-400",
    bestSeason: "10–4 月",
  },
  {
    slug: "france",
    title: "法蘭西漫遊",
    titleEn: "France",
    region: "歐洲",
    country: "法國",
    cover: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    description: "巴黎鐵塔、南法薰衣草、紅酒與芝士，浪漫之都永遠值得再去。",
    status: "completed",
    days: 10,
    style: "文化美食",
    highlights: ["巴黎鐵塔", "羅浮宮", "凡爾賽宮", "南法", "紅酒產區"],
    gradient: "from-blue-500 to-red-400",
    bestSeason: "4–10 月",
  },
  {
    slug: "uk",
    title: "英倫足跡",
    titleEn: "United Kingdom",
    region: "歐洲",
    country: "英國",
    cover: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
    description: "倫敦的大笨鐘與博物館、英式下午茶，帶家人走過的英倫記憶。",
    status: "completed",
    days: 10,
    style: "家庭旅行",
    highlights: ["倫敦", "大英博物館", "大笨鐘", "英式下午茶", "科茲窩"],
    gradient: "from-red-600 to-blue-500",
    bestSeason: "5–9 月",
  },
  {
    slug: "estonia",
    title: "波羅的海驚喜",
    titleEn: "Estonia",
    region: "北歐",
    country: "愛沙尼亞",
    cover: "https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=1200&q=80",
    description: "塔林中世紀老城、數碼遊牧之都，波羅的海最被低估的寶藏小國。",
    status: "completed",
    days: 4,
    style: "城市探索",
    highlights: ["塔林老城", "亞歷山大涅夫斯基大教堂", "市政廳廣場", "Telliskivi創意園區", "波羅的海海岸"],
    gradient: "from-blue-400 to-slate-500",
    bestSeason: "5–9 月",
  },
  {
    slug: "australia",
    title: "南半球陽光",
    titleEn: "Australia",
    region: "大洋洲",
    country: "澳洲",
    cover: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80",
    description: "從珀斯到墨爾本、悉尼到塔斯曼尼亞，南半球的壯闊與自由。",
    status: "completed",
    days: 14,
    style: "自駕探索",
    highlights: ["悉尼歌劇院", "大洋路", "墨爾本", "珀斯", "塔斯曼尼亞"],
    gradient: "from-yellow-400 to-blue-500",
    bestSeason: "10–4 月（夏季）",
  },
  {
    slug: "taiwan",
    title: "寶島台灣",
    titleEn: "Taiwan",
    region: "東亞",
    country: "台灣",
    cover: "https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=1200&q=80",
    description: "台北、台中、宜蘭，夜市小吃與人情味，去了無數次的第二個家。",
    status: "completed",
    days: 5,
    style: "美食休閒",
    highlights: ["台北101", "夜市", "台中", "宜蘭", "日月潭"],
    gradient: "from-green-500 to-blue-400",
    bestSeason: "全年",
  },
  {
    slug: "malaysia",
    title: "南洋風味",
    titleEn: "Malaysia",
    region: "東南亞",
    country: "馬來西亞",
    cover: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1200&q=80",
    description: "檳城的古早味、吉隆坡的雙子塔、沙巴的海島，多元文化的南洋寶藏。",
    status: "completed",
    days: 5,
    style: "美食文化",
    highlights: ["檳城", "吉隆坡", "沙巴", "雙子塔", "娘惹美食"],
    gradient: "from-blue-500 to-yellow-400",
    bestSeason: "3–10 月",
  },
  {
    slug: "singapore",
    title: "獅城花園",
    titleEn: "Singapore",
    region: "東南亞",
    country: "新加坡",
    cover: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80",
    description: "濱海灣花園、金沙酒店、小販中心，精緻與多元並存的花園城市。",
    status: "completed",
    days: 4,
    style: "城市度假",
    highlights: ["濱海灣花園", "金沙酒店", "小販中心", "牛車水", "聖淘沙"],
    gradient: "from-red-500 to-white",
    bestSeason: "全年",
  },
  {
    slug: "usa",
    title: "美國足跡",
    titleEn: "United States",
    region: "北美",
    country: "美國",
    cover: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=80",
    description: "從新奧良的爵士樂到多倫多的…不，這是美國！MDRT 年會的商務之旅。",
    status: "completed",
    days: 7,
    style: "商務旅行",
    highlights: ["新奧爾良", "爵士樂", "法國區", "MDRT年會", "美式美食"],
    gradient: "from-blue-600 to-red-500",
    bestSeason: "全年",
  },
  {
    slug: "cambodia",
    title: "吳哥窟之旅",
    titleEn: "Cambodia",
    region: "東南亞",
    country: "柬埔寨",
    cover: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1200&q=80",
    description: "吳哥窟的日出、塔布隆寺的樹根纏繞，千年高棉帝國的震撼遺跡。",
    status: "completed",
    days: 5,
    style: "歷史探索",
    highlights: ["吳哥窟", "塔布隆寺", "巴戎寺", "暹粒", "洞里薩湖"],
    gradient: "from-amber-600 to-red-500",
    bestSeason: "11–3 月",
  },
  {
    slug: "indonesia",
    title: "千島之國",
    titleEn: "Indonesia",
    region: "東南亞",
    country: "印尼",
    cover: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    description: "峇里島的梯田與神廟、日惹的婆羅浮屠、雅加達的都市叢林。",
    status: "completed",
    days: 5,
    style: "文化海島",
    highlights: ["峇里島", "婆羅浮屠", "日惹", "雅加達", "烏布梯田"],
    gradient: "from-red-500 to-white",
    bestSeason: "4–10 月（旱季）",
  },
  {
    slug: "china",
    title: "神州大地",
    titleEn: "China",
    region: "東亞",
    country: "中國",
    cover: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80",
    description: "北京、成都、桂林、三亞、深圳、佛山、寧波、潮州…走遍大江南北。",
    status: "completed",
    days: 7,
    style: "深度多城",
    highlights: ["北京故宮", "成都熊貓", "桂林山水", "三亞海灘", "深圳"],
    gradient: "from-red-600 to-yellow-500",
    bestSeason: "3–5 月 / 9–11 月",
  },
  {
    slug: "turkey",
    title: "橫跨歐亞",
    titleEn: "Turkey",
    region: "歐亞",
    country: "土耳其",
    cover: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1200&q=80",
    description: "卡帕多奇亞的熱氣球、伊斯坦堡的清真寺、棉花堡的白色梯田。",
    status: "completed",
    days: 10,
    style: "歷史文化",
    highlights: ["卡帕多奇亞", "伊斯坦堡", "棉花堡", "藍色清真寺", "熱氣球"],
    gradient: "from-red-500 to-sky-400",
    bestSeason: "4–6 月 / 9–11 月",
  },
  {
    slug: "palau",
    title: "帛琉潛水",
    titleEn: "Palau",
    region: "大洋洲",
    country: "帛琉",
    cover: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    description: "藍洞、水母湖、牛奶湖，世界級的潛水天堂，海底世界的震撼。",
    status: "completed",
    days: 5,
    style: "潛水探險",
    highlights: ["藍洞", "水母湖", "牛奶湖", "珊瑚礁", "大斷層"],
    gradient: "from-cyan-500 to-blue-600",
    bestSeason: "11–5 月",
  },
  {
    slug: "maldives",
    title: "馬爾代夫船宿",
    titleEn: "Maldives",
    region: "南亞",
    country: "馬爾代夫",
    cover: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
    description: "水上屋、透明海水、無邊際泳池，印度洋上最夢幻的度假天堂。",
    status: "completed",
    days: 5,
    style: "海島度假",
    highlights: ["水上屋", "浮潛", "無邊際泳池", "日落沙灘", "海底餐廳"],
    gradient: "from-cyan-300 to-blue-400",
    bestSeason: "11–4 月",
  },
  {
    slug: "canada",
    title: "楓葉國度",
    titleEn: "Canada",
    region: "北美",
    country: "加拿大",
    cover: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80",
    description: "多倫多的城市活力、落基山的壯闘，帶家人走過的北美大地。",
    status: "completed",
    days: 10,
    style: "家庭旅行",
    highlights: ["多倫多", "尼亞加拉瀑布", "MDRT年會", "楓葉大道", "落基山脈"],
    gradient: "from-red-500 to-white",
    bestSeason: "6–10 月",
  },
  {
    slug: "jordan",
    title: "玫瑰之城",
    titleEn: "Jordan",
    region: "中東",
    country: "約旦",
    cover: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=1200&q=80",
    description: "佩特拉古城、死海漂浮、瓦迪拉姆沙漠，穿越千年的中東秘境。",
    status: "completed",
    days: 6,
    style: "歷史探險",
    highlights: ["佩特拉古城", "死海", "瓦迪拉姆", "安曼", "紅海"],
    gradient: "from-rose-600 to-amber-400",
    bestSeason: "3–5 月 / 9–11 月",
  },
  {
    slug: "doha",
    title: "多哈中轉站",
    titleEn: "Doha, Qatar",
    region: "中東",
    country: "卡塔爾",
    cover: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80",
    description: "珍珠島、伊斯蘭藝術博物館、沙漠衝沙，波斯灣上的奢華與文化交匯。",
    status: "completed",
    days: 3,
    style: "城市體驗",
    highlights: ["珍珠島", "伊斯蘭藝術博物館", "瓦其夫老市場", "沙漠衝沙", "濱海大道"],
    gradient: "from-purple-600 to-amber-400",
    bestSeason: "11–3 月",
  },
  {
    slug: "dubai",
    title: "沙漠奇蹟",
    titleEn: "Dubai, UAE",
    region: "中東",
    country: "阿聯酋",
    cover: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    description: "哈利法塔、棕櫚島、沙漠衝沙，從沙漠中拔地而起的未來之城。",
    status: "completed",
    days: 4,
    style: "城市奢華",
    highlights: ["哈利法塔", "棕櫚島", "杜拜購物中心", "沙漠衝沙", "朱美拉海灘"],
    gradient: "from-amber-400 to-sky-400",
    bestSeason: "11–3 月",
  },
  {
    slug: "perth",
    title: "西澳陽光",
    titleEn: "Perth, Australia",
    region: "大洋洲",
    country: "澳洲",
    cover: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=80",
    description: "印度洋的日落、羅特尼斯島的短尾矮袋鼠、Kings Park 的野花季。",
    status: "completed",
    days: 7,
    style: "自然休閒",
    highlights: ["羅特尼斯島", "Kings Park", "弗里曼特爾", "尖峰石陣", "印度洋日落"],
    gradient: "from-orange-400 to-blue-400",
    bestSeason: "9–11 月（野花季）",
  },
  {
    slug: "cebu",
    title: "宿霧跳島",
    titleEn: "Cebu, Philippines",
    region: "東南亞",
    country: "菲律賓",
    cover: "https://images.unsplash.com/photo-1573790387438-4da905039392?auto=format&fit=crop&w=1200&q=80",
    description: "與鯨鯊共泳、卡瓦桑瀑布、薄荷島眼鏡猴，菲律賓的熱帶天堂。",
    status: "completed",
    days: 5,
    style: "海島冒險",
    highlights: ["鯨鯊共泳", "卡瓦桑瀑布", "薄荷島", "眼鏡猴", "麥克坦島"],
    gradient: "from-cyan-400 to-green-400",
    bestSeason: "1–5 月（旱季）",
  },
  {
    slug: "tasmania",
    title: "塔斯曼尼亞秘境",
    titleEn: "Tasmania",
    region: "大洋洲",
    country: "澳洲",
    cover: "https://images.unsplash.com/photo-1516117172878-fd2c41f4a759?auto=format&fit=crop&w=1200&q=80",
    description: "搖籃山、酒杯灣、薰衣草農場，澳洲最南端的世外桃源。",
    status: "completed",
    days: 7,
    style: "自然自駕",
    highlights: ["搖籃山", "酒杯灣", "荷巴特", "薰衣草農場", "塔斯曼半島"],
    gradient: "from-emerald-500 to-teal-400",
    bestSeason: "12–2 月（夏季）",
  },
  {
    slug: "hokkaido",
    title: "北海道四季",
    titleEn: "Hokkaido",
    region: "東亞",
    country: "日本",
    cover: "https://images.unsplash.com/photo-1491002052546-bf38f186af56?auto=format&fit=crop&w=1200&q=80",
    description: "富良野花田、小樽運河、札幌拉麵、雪祭，四季皆美的北國大地。",
    status: "completed",
    days: 7,
    style: "自然美食",
    highlights: ["富良野", "小樽運河", "札幌", "旭川動物園", "登別溫泉"],
    gradient: "from-sky-400 to-purple-400",
    bestSeason: "7–8 月（花季）/ 12–2 月（雪季）",
  },
  {
    slug: "nagoya",
    title: "名古屋散策",
    titleEn: "Nagoya",
    region: "東亞",
    country: "日本",
    cover: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80",
    description: "名古屋城、熱田神宮、鰻魚飯三吃，中部地方的低調魅力。",
    status: "completed",
    days: 4,
    style: "文化美食",
    highlights: ["名古屋城", "熱田神宮", "鰻魚飯", "大須商店街", "白川鄉"],
    gradient: "from-amber-500 to-red-400",
    bestSeason: "3–5 月 / 10–11 月",
  },
  {
    slug: "osaka",
    title: "大阪食倒",
    titleEn: "Osaka",
    region: "東亞",
    country: "日本",
    cover: "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=1200&q=80",
    description: "道頓堀的霓虹、章魚燒與串炸、大阪城的壯觀，天下的廚房。",
    status: "completed",
    days: 4,
    style: "美食城市",
    highlights: ["道頓堀", "大阪城", "心齋橋", "章魚燒", "環球影城"],
    gradient: "from-orange-500 to-red-500",
    bestSeason: "3–5 月 / 10–11 月",
  },
  {
    slug: "shantou",
    title: "潮汕美食行",
    titleEn: "Shantou",
    region: "東亞",
    country: "中國",
    cover: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
    description: "牛肉火鍋、腸粉、功夫茶，潮汕是中國最被低估的美食聖地。",
    status: "completed",
    days: 4,
    style: "美食之旅",
    highlights: ["牛肉火鍋", "潮州古城", "功夫茶", "腸粉", "老城騎樓"],
    gradient: "from-red-500 to-orange-400",
    bestSeason: "10–3 月",
  },
  {
    slug: "fukuoka",
    title: "博多拉麵行",
    titleEn: "Fukuoka",
    region: "東亞",
    country: "日本",
    cover: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80",
    description: "博多拉麵、屋台文化、太宰府天滿宮，九州的熱情入口。",
    status: "completed",
    days: 4,
    style: "美食文化",
    highlights: ["博多拉麵", "屋台", "太宰府天滿宮", "中洲", "柳川"],
    gradient: "from-red-400 to-pink-400",
    bestSeason: "3–5 月 / 10–11 月",
  },
  {
    slug: "okinawa",
    title: "沖繩藍海",
    titleEn: "Okinawa",
    region: "東亞",
    country: "日本",
    cover: "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=1200&q=80",
    description: "美麗海水族館、萬座毛、古宇利島，日本最南端的熱帶天堂。",
    status: "completed",
    days: 5,
    style: "海島家庭",
    highlights: ["美麗海水族館", "萬座毛", "古宇利島", "首里城", "國際通"],
    gradient: "from-cyan-400 to-blue-500",
    bestSeason: "4–10 月",
  },
];
